// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: amiibo/v1/amiibo.proto

package amiibov1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Amiibo_Type int32

const (
	Amiibo_UNSPECIFIED Amiibo_Type = 0
	Amiibo_CARD        Amiibo_Type = 1
	Amiibo_FIGURE      Amiibo_Type = 2
	Amiibo_YARN        Amiibo_Type = 3
)

// Enum value maps for Amiibo_Type.
var (
	Amiibo_Type_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CARD",
		2: "FIGURE",
		3: "YARN",
	}
	Amiibo_Type_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CARD":        1,
		"FIGURE":      2,
		"YARN":        3,
	}
)

func (x Amiibo_Type) Enum() *Amiibo_Type {
	p := new(Amiibo_Type)
	*p = x
	return p
}

func (x Amiibo_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Amiibo_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_amiibo_v1_amiibo_proto_enumTypes[0].Descriptor()
}

func (Amiibo_Type) Type() protoreflect.EnumType {
	return &file_amiibo_v1_amiibo_proto_enumTypes[0]
}

func (x Amiibo_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Amiibo_Type.Descriptor instead.
func (Amiibo_Type) EnumDescriptor() ([]byte, []int) {
	return file_amiibo_v1_amiibo_proto_rawDescGZIP(), []int{2, 0}
}

type GetAmiiboRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetAmiiboRequest) Reset() {
	*x = GetAmiiboRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amiibo_v1_amiibo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmiiboRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmiiboRequest) ProtoMessage() {}

func (x *GetAmiiboRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amiibo_v1_amiibo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmiiboRequest.ProtoReflect.Descriptor instead.
func (*GetAmiiboRequest) Descriptor() ([]byte, []int) {
	return file_amiibo_v1_amiibo_proto_rawDescGZIP(), []int{0}
}

func (x *GetAmiiboRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAmiiboResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amiibo []*Amiibo `protobuf:"bytes,1,rep,name=amiibo,proto3" json:"amiibo,omitempty"`
}

func (x *GetAmiiboResponse) Reset() {
	*x = GetAmiiboResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amiibo_v1_amiibo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmiiboResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmiiboResponse) ProtoMessage() {}

func (x *GetAmiiboResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amiibo_v1_amiibo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmiiboResponse.ProtoReflect.Descriptor instead.
func (*GetAmiiboResponse) Descriptor() ([]byte, []int) {
	return file_amiibo_v1_amiibo_proto_rawDescGZIP(), []int{1}
}

func (x *GetAmiiboResponse) GetAmiibo() []*Amiibo {
	if x != nil {
		return x.Amiibo
	}
	return nil
}

type Amiibo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Character    string      `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	Name         string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AmiiboSeries string      `protobuf:"bytes,3,opt,name=amiibo_series,json=amiiboSeries,proto3" json:"amiibo_series,omitempty"`
	ImageUrl     string      `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Type         Amiibo_Type `protobuf:"varint,5,opt,name=type,proto3,enum=clutch.amiibo.v1.Amiibo_Type" json:"type,omitempty"`
}

func (x *Amiibo) Reset() {
	*x = Amiibo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amiibo_v1_amiibo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Amiibo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amiibo) ProtoMessage() {}

func (x *Amiibo) ProtoReflect() protoreflect.Message {
	mi := &file_amiibo_v1_amiibo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amiibo.ProtoReflect.Descriptor instead.
func (*Amiibo) Descriptor() ([]byte, []int) {
	return file_amiibo_v1_amiibo_proto_rawDescGZIP(), []int{2}
}

func (x *Amiibo) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *Amiibo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Amiibo) GetAmiiboSeries() string {
	if x != nil {
		return x.AmiiboSeries
	}
	return ""
}

func (x *Amiibo) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Amiibo) GetType() Amiibo_Type {
	if x != nil {
		return x.Type
	}
	return Amiibo_UNSPECIFIED
}

var File_amiibo_v1_amiibo_proto protoreflect.FileDescriptor

var file_amiibo_v1_amiibo_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6d, 0x69, 0x69,
	0x62, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68,
	0x2e, 0x61, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x20, 0x01, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x45, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x6d, 0x69, 0x69, 0x62,
	0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68,
	0x2e, 0x61, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6d, 0x69, 0x69, 0x62,
	0x6f, 0x52, 0x06, 0x61, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x22, 0xe8, 0x01, 0x0a, 0x06, 0x41, 0x6d,
	0x69, 0x69, 0x62, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6d, 0x69, 0x69, 0x62, 0x6f,
	0x5f, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x6d, 0x69, 0x69, 0x62, 0x6f, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2e,
	0x61, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6d, 0x69, 0x69, 0x62, 0x6f,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x37, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x41, 0x52, 0x44, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x49, 0x47, 0x55, 0x52, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x59, 0x41,
	0x52, 0x4e, 0x10, 0x03, 0x32, 0x82, 0x01, 0x0a, 0x09, 0x41, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x41,
	0x50, 0x49, 0x12, 0x75, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x12,
	0x22, 0x2e, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2e, 0x61, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2e, 0x61, 0x6d, 0x69,
	0x69, 0x62, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x69, 0x69, 0x62, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19,
	0x22, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x2f, 0x67, 0x65, 0x74,
	0x41, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x3a, 0x01, 0x2a, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x66, 0x63, 0x61, 0x62, 0x72, 0x61,
	0x2f, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2d, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6d, 0x69, 0x69, 0x62, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x6d, 0x69,
	0x69, 0x62, 0x6f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_amiibo_v1_amiibo_proto_rawDescOnce sync.Once
	file_amiibo_v1_amiibo_proto_rawDescData = file_amiibo_v1_amiibo_proto_rawDesc
)

func file_amiibo_v1_amiibo_proto_rawDescGZIP() []byte {
	file_amiibo_v1_amiibo_proto_rawDescOnce.Do(func() {
		file_amiibo_v1_amiibo_proto_rawDescData = protoimpl.X.CompressGZIP(file_amiibo_v1_amiibo_proto_rawDescData)
	})
	return file_amiibo_v1_amiibo_proto_rawDescData
}

var file_amiibo_v1_amiibo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_amiibo_v1_amiibo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_amiibo_v1_amiibo_proto_goTypes = []interface{}{
	(Amiibo_Type)(0),          // 0: clutch.amiibo.v1.Amiibo.Type
	(*GetAmiiboRequest)(nil),  // 1: clutch.amiibo.v1.GetAmiiboRequest
	(*GetAmiiboResponse)(nil), // 2: clutch.amiibo.v1.GetAmiiboResponse
	(*Amiibo)(nil),            // 3: clutch.amiibo.v1.Amiibo
}
var file_amiibo_v1_amiibo_proto_depIdxs = []int32{
	3, // 0: clutch.amiibo.v1.GetAmiiboResponse.amiibo:type_name -> clutch.amiibo.v1.Amiibo
	0, // 1: clutch.amiibo.v1.Amiibo.type:type_name -> clutch.amiibo.v1.Amiibo.Type
	1, // 2: clutch.amiibo.v1.AmiiboAPI.GetAmiibo:input_type -> clutch.amiibo.v1.GetAmiiboRequest
	2, // 3: clutch.amiibo.v1.AmiiboAPI.GetAmiibo:output_type -> clutch.amiibo.v1.GetAmiiboResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_amiibo_v1_amiibo_proto_init() }
func file_amiibo_v1_amiibo_proto_init() {
	if File_amiibo_v1_amiibo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_amiibo_v1_amiibo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAmiiboRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amiibo_v1_amiibo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAmiiboResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amiibo_v1_amiibo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Amiibo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_amiibo_v1_amiibo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_amiibo_v1_amiibo_proto_goTypes,
		DependencyIndexes: file_amiibo_v1_amiibo_proto_depIdxs,
		EnumInfos:         file_amiibo_v1_amiibo_proto_enumTypes,
		MessageInfos:      file_amiibo_v1_amiibo_proto_msgTypes,
	}.Build()
	File_amiibo_v1_amiibo_proto = out.File
	file_amiibo_v1_amiibo_proto_rawDesc = nil
	file_amiibo_v1_amiibo_proto_goTypes = nil
	file_amiibo_v1_amiibo_proto_depIdxs = nil
}
