// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: amiibo/v1/amiibo.proto

package amiibov1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetAmiiboRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetAmiiboRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAmiiboRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAmiiboRequestMultiError, or nil if none found.
func (m *GetAmiiboRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAmiiboRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetName()) < 1 {
		err := GetAmiiboRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetAmiiboRequestMultiError(errors)
	}

	return nil
}

// GetAmiiboRequestMultiError is an error wrapping multiple validation errors
// returned by GetAmiiboRequest.ValidateAll() if the designated constraints
// aren't met.
type GetAmiiboRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAmiiboRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAmiiboRequestMultiError) AllErrors() []error { return m }

// GetAmiiboRequestValidationError is the validation error returned by
// GetAmiiboRequest.Validate if the designated constraints aren't met.
type GetAmiiboRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAmiiboRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAmiiboRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAmiiboRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAmiiboRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAmiiboRequestValidationError) ErrorName() string { return "GetAmiiboRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetAmiiboRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAmiiboRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAmiiboRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAmiiboRequestValidationError{}

// Validate checks the field values on GetAmiiboResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetAmiiboResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAmiiboResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAmiiboResponseMultiError, or nil if none found.
func (m *GetAmiiboResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAmiiboResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAmiibo() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAmiiboResponseValidationError{
						field:  fmt.Sprintf("Amiibo[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAmiiboResponseValidationError{
						field:  fmt.Sprintf("Amiibo[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAmiiboResponseValidationError{
					field:  fmt.Sprintf("Amiibo[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetAmiiboResponseMultiError(errors)
	}

	return nil
}

// GetAmiiboResponseMultiError is an error wrapping multiple validation errors
// returned by GetAmiiboResponse.ValidateAll() if the designated constraints
// aren't met.
type GetAmiiboResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAmiiboResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAmiiboResponseMultiError) AllErrors() []error { return m }

// GetAmiiboResponseValidationError is the validation error returned by
// GetAmiiboResponse.Validate if the designated constraints aren't met.
type GetAmiiboResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAmiiboResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAmiiboResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAmiiboResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAmiiboResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAmiiboResponseValidationError) ErrorName() string {
	return "GetAmiiboResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAmiiboResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAmiiboResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAmiiboResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAmiiboResponseValidationError{}

// Validate checks the field values on Amiibo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Amiibo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Amiibo with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AmiiboMultiError, or nil if none found.
func (m *Amiibo) ValidateAll() error {
	return m.validate(true)
}

func (m *Amiibo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Character

	// no validation rules for Name

	// no validation rules for AmiiboSeries

	// no validation rules for ImageUrl

	// no validation rules for Type

	if len(errors) > 0 {
		return AmiiboMultiError(errors)
	}

	return nil
}

// AmiiboMultiError is an error wrapping multiple validation errors returned by
// Amiibo.ValidateAll() if the designated constraints aren't met.
type AmiiboMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AmiiboMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AmiiboMultiError) AllErrors() []error { return m }

// AmiiboValidationError is the validation error returned by Amiibo.Validate if
// the designated constraints aren't met.
type AmiiboValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AmiiboValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AmiiboValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AmiiboValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AmiiboValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AmiiboValidationError) ErrorName() string { return "AmiiboValidationError" }

// Error satisfies the builtin error interface
func (e AmiiboValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAmiibo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AmiiboValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AmiiboValidationError{}
